### ISSUE TITLE
Functions defined as other functions are wrapped too often

### ISSUE THREAD

**Issue by jo-hanna1997** [FreeProving/free-compiler#3]
When defining functions as other (partial) functions the compiled code adds too many monad wrappings.

For example the accumulative reverse

```haskell
rev :: [a] -> [a]
rev = rev' []

rev' :: [a] -> [a] ->[a]
rev' xs [] = xs
rev' xs (y:ys) = rev' (y:xs) ys
```

becomes

```coq
Definition rev (Shape : Type) (Pos : Shape -> Type) {a : Type}
   : Free Shape Pos (Free Shape Pos (List Shape Pos a) ->
           Free Shape Pos (List Shape Pos a)) :=
  pure (fun x_0 => @rev' Shape Pos a (@Nil Shape Pos a) x_0).
```

but should be 

```coq
Definition rev (Shape : Type) (Pos : Shape -> Type) {a : Type}
   : Free Shape Pos (List Shape Pos a) ->
           Free Shape Pos (List Shape Pos a) :=
  pure (fun x_0 => @rev'_0 Shape Pos a (@Nil Shape Pos a) x_0).
```

or 

```coq
... :=    @rev' Shape Pos a (@Nil Shape Pos a).
```

**Comment by just95** [comment]
Actually, this behavior is intended. If `rev` was defined as follows, you would be right.

```haskell
rev :: [a] -> [a]
rev xs = rev' [] xs
```

In this case we know, that any partial application of `rev` does not have an effect. This allows us to write `rev xs` instead of `rev >>= fun f => f xs` in Coq.

However, in your point-free version

```haskell
rev :: [a] -> [a]
rev = rev' []
```

we cannot say for sure that `rev` does not have an effect without performing extensive (probably undecidable) program analysis. For example, consider the following alternative definition.

```haskell
rev :: [a] -> [a]
rev = undefined
```

Invoking `rev` in Coq using `rev xs` as above, would not be valid. We have to bind the function wrapped in `rev` in order to invoke it, i.e., `rev >>= fun f => f xs`.

See also Sections 3.3.2 and 3.4.1 of my [Bachelor's Thesis](https://freeproving.github.io/free-compiler/thesis/Andresen2019.pdf) for more detail.

**Comment by just95** [comment]
I've spend some more time thinking about this issue and came to the conclusion that it might be easier to realize your expected behavior than I initially assumed. Some background information: the compiler currently performs so called [η-conversions](https://wiki.haskell.org/Eta_conversion) to the Haskell code (or the intermediate representation to be more precise) in order to make sure that every function and constructor is fully applied.
In your example `rev'` is applied to only one argument, but expects two arguments. Thus, the right-hand side of `rev` is η-abstracted once. The following code is generated.

```haskell
rev :: [a] -> [a]
rev = \xs -> rev' [] xs
```

where `xs` is a fresh variable. You can observe that this is done by looking at the generated Coq code. The `pure (fun x_0 => @rev' Shape Pos a (@Nil Shape Pos a) x_0)` is actually the translation of the newly introduced lambda abstraction.

What I've now noticed is that this version now looks remarkably similar to the version I've mentioned in my post above where the additional `Free` can be avoided. It should be straight forward to adapt the compiler such that

```haskell
rev :: [a] -> [a]
rev xs = rev' [] xs
```

is generated instead without performing any complex program analysis.

I am going to change the label of this issue to <kbd>[enhancement](https://github.com/FreeProving/free-compiler/labels/enhancement)</kbd>. Furthermore, I think that this is going to be a <kbd>[good first issue](https://github.com/FreeProving/free-compiler/labels/good%20first%20issue)</kbd> to work on for new contributors.

A good place to start is the `EtaConversionPass`. Incorporating the change directly into the `EtaConversionPass` should be a matter of a few line changes. Also remember to update the existing documentation and add test cases.
