### ISSUE TITLE
Generated Coq code defines functions in uncompilable order and misses an argument unpacking

### ISSUE THREAD

**Issue by jo-hanna1997** [FreeProving/free-compiler#7]
### Description

The generated code defines two functions (a called and a calling one) in the wrong order, such that the called one is not in scope. Simply interchanging the functions solves this.

Moreover one of the generated functions rightly defines a local function `f_0` but never calls it. Instead the function `f` (not in scope) is called and the unpacking scheme using `>>=` is ignored.

### Steps to Reproduce

Compile the following Haskell code:

```haskell
module ZigZag where

data Tree a = Leaf a | Node (Tree a) (Tree a)


{-# FreeC zigzag DECREASES ON ARGUMENT 1 #-}
zigzag :: Tree Bool -> Bool
zigzag t = zig t

zig:: Tree Bool -> Bool
zig (Leaf n) = n
zig (Node t1 t2) = zag t1

zag:: Tree Bool -> Bool
zag (Leaf n) = n
zag (Node t1 t2) = zigzag t2
```
with the following command

```bash
freec --transform-pattern-matching ZigZag.hs
```

#### Expected behavior

The example above should produce valid Coq code.

#### Actual behavior

In the generated helper function `zag_0`, the definition of `zigzag` is inlined but the definition of `zig` is not inlined recursively. The main function for `zig` is not yet defined at this point.

```coq
Fixpoint zag_0 (Shape : Type) (Pos : Shape -> Type) (a7
                 : Tree Shape Pos (Bool Shape Pos)) {struct a7} : Free Shape Pos (Bool Shape
                                                                                       Pos)
           := match a7 with
              | leaf a8 => a8
              | node a10 a11 => zig Shape Pos a11 (* <-- not inlined correctly *)
              end
with zig_0 (Shape : Type) (Pos : Shape -> Type) (a0
             : Tree Shape Pos (Bool Shape Pos)) {struct a0} : Free Shape Pos (Bool Shape
                                                                                   Pos)
       := match a0 with
          | leaf a1 => a1
          | node a3 a4 =>
              a3 >>= (fun (a3_0 : Tree Shape Pos (Bool Shape Pos)) => zag_0 Shape Pos a3_0)
          end.
```

Additionally, the generated main functions occur out of order.

```coq
Definition zag (Shape : Type) (Pos : Shape -> Type) (a7
    : Free Shape Pos (Tree Shape Pos (Bool Shape Pos)))
   : Free Shape Pos (Bool Shape Pos) :=
  a7 >>= (fun (a7_0 : Tree Shape Pos (Bool Shape Pos)) => zag_0 Shape Pos a7_0).

Definition zigzag (Shape : Type) (Pos : Shape -> Type) (t
    : Free Shape Pos (Tree Shape Pos (Bool Shape Pos)))
   : Free Shape Pos (Bool Shape Pos) :=
  zig Shape Pos t. (* <-- `zig` is used here but defined later *)

Definition zig (Shape : Type) (Pos : Shape -> Type) (a0
    : Free Shape Pos (Tree Shape Pos (Bool Shape Pos)))
   : Free Shape Pos (Bool Shape Pos) :=
  a0 >>= (fun (a0_0 : Tree Shape Pos (Bool Shape Pos)) => zig_0 Shape Pos a0_0).
```

### Versions

 - `freec --version`: 0.1.0.0
 - `ghc --version`: 8.6.5
 - `cabal --version`: 2.4.1.0
 - `coqc --version`: 8.9.0
 - OS: Windows

### Known workarounds

Replacing the last line by `zag (Node t1 t2) = zig t2` works just fine.

**Comment by just95** [comment]
Thanks for the bug report. I was able to reproduce the problem. At the first glance I think that fixing this bug should be straight forward. Thus, I believe that this is a good first issue for new contributors. The following are some pointers for what needs to be done and where to start.
 - Inlining of function declarations is defined in the module `FreeC.IR.Inlining`.
 - After inlining a function declaration, inlining has to be performed recursively on the right-hand side in order to fix the first part of this bug. Does this process always terminate?
 - In order to fix the order of the generated main functions, the translation of recursive functions by the Coq backend has to be adapted. Have a look at `FreeC.Backend.Coq.Converter.FuncDecl.Rec.WithHelpers`.
 - An example for how declarations can be sorted according to their dependencies can be found in `FreeC.Backend.Coq.Converter.TypeDecl`.
 - Make sure to update documentation and add appropriate test cases.
